version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  redis:
    image: redis:alpine
    container_name: "Redis_Database"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server
